export let questions = [
  {
    question:
      "Anything1njasn sanlsa lasnl salnsa aslnas ,asnkjsbaskj sabas askj asmabsksa sakasm, sanbkjsa,m skjas m kasjsan ,asbkjas mnasbk s bkjas aslknn ,sa",
    opt1: "1 jasn sanlsa lasnl salnsa aslnas ,asnkjsbaskj sabas askj asmabsksa sakasm, sanbkjsa,m skjas m kasjsan ,asbkjas mnasbk s bkjas aslknn ,sa1",
    opt2: "22",
    opt3: "33",
    opt4: "44",
    answer: 1,
  },
  {
    question: "Anything2",
    opt1: "11",
    opt2: "22",
    opt3: "33",
    opt4: "44",
    answer: 2,
  },
  {
    question: "Anything3",
    opt1: "11",
    opt2: "22",
    opt3: "33",
    opt4: "44",
    answer: 3,
  },
  {
    question: "Anything4",
    opt1: "11",
    opt2: "22",
    opt3: "33",
    opt4: "44",
    answer: 4,
  },
  {
    question: "Anything5",
    opt1: "11",
    opt2: "22",
    opt3: "33",
    opt4: "44",
    answer: 1,
  },
  {
    question: "Anything6",
    opt1: "11",
    opt2: "22",
    opt3: "33",
    opt4: "44",
    answer: 2,
  },
  {
    question: "Anything1",
    opt1: "11",
    opt2: "22",
    opt3: "33",
    opt4: "44",
    answer: 1,
  },
  {
    question: "Anything2",
    opt1: "11",
    opt2: "22",
    opt3: "33",
    opt4: "44",
    answer: 2,
  },
  {
    question: "Anything3",
    opt1: "11",
    opt2: "22",
    opt3: "33",
    opt4: "44",
    answer: 3,
  },
  {
    question: "Anything4",
    opt1: "11",
    opt2: "22",
    opt3: "33",
    opt4: "44",
    answer: 4,
  },
  {
    question: "Anything5",
    opt1: "11",
    opt2: "22",
    opt3: "33",
    opt4: "44",
    answer: 1,
  },
  {
    question: "Anything6",
    opt1: "11",
    opt2: "22",
    opt3: "33",
    opt4: "44",
    answer: 2,
  },
];
