export const REGISTER_INITIATED = "REGISTER_INITIATED";
export const REGISTER_SUCCESS= "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_RESET = "REGISTER_RESET";